---
- name: copy the content with tags
  hosts: dev
  become: yes
  tasks:
    - name: copy the blue server content
      ansible.builtin.copy:
        content: "Welcome to Blue Server"
        dest: /var/www/html/index.html
      tags: [never,blue]

    - name: copy the green server content
      ansible.builtin.copy:
        content: "Welcome to Green Server"
        dest: /var/www/html/index.html
      tags: [never,green]

