---
- name: copy the content with tags
  hosts: dev
  become: yes
  tasks:
    - name: web content and tag for blue server
      ansible.builtin.copy:
        content: "Welcome to Blue Server"
        dest: /var/www/html/index.html
      tags: [never,blue]

    - name: web content and tag for green server
      ansible.builtin.copy:
        content: "Welcome to Green Server"
        dest: /var/www/html/index.html
      tags: [never,green]
