---
- name: Copy the content to webserver
  hosts: dev
  become: yes
  tasks:
    - name: copy the content to blue server
      ansible.builtin.copy:
        content: "Welcome to Blue server"
        dest: /var/www/html/index.html
      tags: [never,blue]

    - name: copy the content to green server
      ansible.builtin.copy:
        content: "Welcome to green server"
        dest: /var/www/html/index.html
      tags: [never,green]

