---
- name: Copy the content to webserver
  hosts: dev
  become: yes
  tasks:
    - name: copy the blue content
      ansible.builtin.copy:
        content: "Welcome to Blue server"
        dest: /var/www/html/index.html
      tags: [never,blue]

    - name: copy the green content
      ansible.builtin.copy:
        content: "Welcome to Green server"
        dest: /var/www/html/index.html
      tags: [never,green]

    
